[package]
name = "sse-steam"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sse-core = { path = "../sse-core" }
sse-codecs = { path = "../sse-codecs" }
sse-sys = { path = "../sse-sys" }
sse-xray = { path = "../sse-xray" }

[lints]
workspace = true
