name = "save-editor-downloads"
main = "worker.mjs"
compatibility_date = "2026-09-01"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "save-editor-downloads"

[[ratelimits]]
name = "DIAGNOSTICS_RATE_LIMITER"
namespace_id = "519021"

[ratelimits.simple]
limit = 30
period = 60

[observability]
enabled = false
