[package]
name = "sse-lint"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sse-core = { path = "../sse-core" }
sse-content = { path = "../sse-content" }
sse-fixes = { path = "../sse-fixes" }
sse-codecs = { path = "../sse-codecs" }

[lints]
workspace = true
