[package]
name = "sse-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sse-core = { path = "../sse-core" }
sse-codecs = { path = "../sse-codecs" }
sse-storage = { path = "../sse-storage" }
sse-sys = { path = "../sse-sys" }

[lints]
workspace = true
