//! Dependency-free raw DEFLATE encoder with lazy LZ77 matching.
use sse_core::{Error, Result};
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum Level{Fast,Default}
struct Bits{out:Vec<u8>,bits:u64,count:u8}
impl Bits{fn new()->Self{Self{out:Vec::new(),bits:0,count:0}}fn put(&mut self,v:u32,n:u8)->Result<()>{if n>24{return Err(Error::damaged("deflate bit width"));}self.bits|=u64::from(v)<<self.count;self.count=self.count.saturating_add(n);while self.count>=8{self.out.push(u8::try_from(self.bits&255).map_err(|_|Error::damaged("deflate byte"))?);self.bits>>=8;self.count-=8;}Ok(())}fn finish(mut self)->Vec<u8>{if self.count>0{self.out.push(u8::try_from(self.bits&255).unwrap_or_default());}self.out}}
fn rev(mut v:u16,n:u8)->u16{let mut r=0u16;for _ in 0..n{r=(r<<1)|(v&1);v>>=1;}r}
fn fixed(sym:u16)->(u16,u8){match sym{0..=143=>(rev(sym+0x30,8),8),144..=255=>(rev(sym-144+0x190,9),9),256..=279=>(rev(sym-256,7),7),_=>(rev(sym-280+0xc0,8),8)}}
const LB:[usize;29]=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258];
const LE:[u8;29]=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0];
const DB:[usize;30]=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577];
const DE:[u8;30]=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];
fn emit_lit(w:&mut Bits,s:u16)->Result<()>{let(c,n)=fixed(s);w.put(u32::from(c),n)}
fn emit_match(w:&mut Bits,len:usize,dist:usize)->Result<()>{let li=LB.iter().enumerate().rev().find(|(_,b)|**b<=len).map(|(i,_)|i).ok_or_else(||Error::damaged("deflate length"))?;emit_lit(w,u16::try_from(257+li).map_err(|_|Error::damaged("length symbol"))?)?;let eb=*LE.get(li).ok_or_else(||Error::damaged("length extra"))?;w.put(u32::try_from(len.saturating_sub(*LB.get(li).unwrap_or(&len))).map_err(|_|Error::damaged("length extra"))?,eb)?;let di=DB.iter().enumerate().rev().find(|(_,b)|**b<=dist).map(|(i,_)|i).ok_or_else(||Error::damaged("distance"))?;w.put(u32::from(rev(u16::try_from(di).map_err(|_|Error::damaged("distance symbol"))?,5)),5)?;let de=*DE.get(di).ok_or_else(||Error::damaged("distance extra"))?;w.put(u32::try_from(dist.saturating_sub(*DB.get(di).unwrap_or(&dist))).map_err(|_|Error::damaged("distance extra"))?,de)}
fn hash3(d:&[u8],p:usize)->Option<usize>{let a=usize::from(*d.get(p)?);let b=usize::from(*d.get(p.checked_add(1)?)?);let c=usize::from(*d.get(p.checked_add(2)?)?);Some(((a*251+b)*251+c)&0x7fff)}
fn best(d:&[u8],p:usize,head:&[Option<usize>],prev:&[Option<usize>],limit:usize)->(usize,usize){let Some(h)=hash3(d,p)else{return(0,0)};let mut q=head.get(h).and_then(|x|*x);let mut best=(0,0);let mut steps=0usize;while let Some(pos)=q{if p<=pos||p.saturating_sub(pos)>32768{break;}let max=258.min(d.len().saturating_sub(p));let mut n=0usize;while n<max&&d.get(pos.saturating_add(n))==d.get(p.saturating_add(n)){n=n.saturating_add(1);}if n>=3&&n>best.0{best=(n,p-pos);if n==258{break;}}steps=steps.saturating_add(1);if steps>=limit{break;}q=prev.get(pos).and_then(|x|*x);}best}
/// Compresses to a raw RFC1951 stream. The encoder uses a fixed-Huffman block and lazy hash-chain matching.
pub fn compress_raw(input:&[u8],level:Level)->Result<Vec<u8>>{let mut w=Bits::new();w.put(1,1)?;w.put(1,2)?;let mut head=vec![None;32768];let mut prev=vec![None;input.len()];let chain=if level==Level::Fast{16}else{128};let mut p=0usize;while p<input.len(){let m=best(input,p,&head,&prev,chain);if let Some(h)=hash3(input,p){if let Some(slot)=prev.get_mut(p){*slot=head.get(h).and_then(|x|*x);}if let Some(slot)=head.get_mut(h){*slot=Some(p);}}
 let use_match=if m.0>=3&&p.saturating_add(1)<input.len(){let n=best(input,p+1,&head,&prev,chain/2+1);!(n.0>m.0.saturating_add(1))}else{m.0>=3};if use_match{emit_match(&mut w,m.0,m.1)?;let end=p.saturating_add(m.0);let mut q=p.saturating_add(1);while q<end{if let Some(h)=hash3(input,q){if let Some(slot)=prev.get_mut(q){*slot=head.get(h).and_then(|x|*x);}if let Some(slot)=head.get_mut(h){*slot=Some(q);}}q=q.saturating_add(1);}p=end;}else{emit_lit(&mut w,u16::from(*input.get(p).ok_or_else(||Error::damaged("deflate input"))?))?;p=p.saturating_add(1);}}
emit_lit(&mut w,256)?;Ok(w.finish())}
#[cfg(test)]mod tests{use super::*;#[test]fn empty_is_valid_shape(){let v=compress_raw(b"",Level::Default).unwrap_or_default();assert!(!v.is_empty());}#[test]fn repetitive_compresses(){let d=vec![b'a';10000];let v=compress_raw(&d,Level::Default).unwrap_or_default();assert!(v.len()<200);}}