//! Vorbis-I header validation and PCM decode entry point.
use sse_core::{Error,Result};
use crate::ogg;
#[derive(Clone,Debug,PartialEq,Eq)]pub struct Pcm{pub channels:u8,pub rate:u32,pub samples:Vec<i16>}
struct Bits<'a>{d:&'a[u8],p:usize}impl<'a>Bits<'a>{fn new(d:&'a[u8])->Self{Self{d,p:0}}fn read(&mut self,n:u8)->Result<u32>{if n>32{return Err(Error::damaged("Vorbis bit width"));}let mut v=0u32;for i in 0..n{let byte=*self.d.get(self.p/8).ok_or_else(||Error::damaged("truncated Vorbis bits"))?;let bit=(byte>>(self.p%8))&1;v|=u32::from(bit)<<i;self.p=self.p.checked_add(1).ok_or_else(||Error::damaged("Vorbis bit offset"))?;}Ok(v)}}
fn header<'a>(p:&'a[u8],kind:u8)->Result<&'a[u8]>{if p.first()!=Some(&kind)||p.get(1..7)!=Some(b"vorbis"){return Err(Error::damaged("invalid Vorbis header"));}p.get(7..).ok_or_else(||Error::damaged("short Vorbis header"))}
fn identification(p:&[u8])->Result<(u8,u32,usize,usize)>{let d=header(p,1)?;if d.len()<23{return Err(Error::damaged("short Vorbis identification"));}let ver=u32::from_le_bytes(<[u8;4]>::try_from(d.get(0..4).ok_or_else(||Error::damaged("Vorbis version"))?).map_err(|_|Error::damaged("Vorbis version"))?);if ver!=0{return Err(Error::Refused("unsupported Vorbis version".to_owned()));}let ch=*d.get(4).ok_or_else(||Error::damaged("Vorbis channels"))?;if ch==0||ch>8{return Err(Error::Refused("unsupported Vorbis channel count".to_owned()));}let rate=u32::from_le_bytes(<[u8;4]>::try_from(d.get(5..9).ok_or_else(||Error::damaged("Vorbis rate"))?).map_err(|_|Error::damaged("Vorbis rate"))?);if rate==0{return Err(Error::damaged("zero Vorbis sample rate"));}let bs=*d.get(21).ok_or_else(||Error::damaged("Vorbis block sizes"))?;let a=1usize.checked_shl(u32::from(bs&15)).ok_or_else(||Error::damaged("Vorbis block size"))?;let b=1usize.checked_shl(u32::from(bs>>4)).ok_or_else(||Error::damaged("Vorbis block size"))?;if a<64||b<a||b>8192{return Err(Error::damaged("invalid Vorbis block sizes"));}if d.get(22).copied().unwrap_or(0)&1==0{return Err(Error::damaged("Vorbis identification framing bit"));}Ok((ch,rate,a,b))}
fn validate_comment(p:&[u8])->Result<()> {let d=header(p,3)?;let mut pos=0usize;let take32=|d:&[u8],p:&mut usize|->Result<usize>{let s=d.get(*p..p.saturating_add(4)).ok_or_else(||Error::damaged("short Vorbis comment"))?;*p=p.saturating_add(4);usize::try_from(u32::from_le_bytes(<[u8;4]>::try_from(s).map_err(|_|Error::damaged("comment length"))?)).map_err(|_|Error::damaged("comment length"))};let vendor=take32(d,&mut pos)?;pos=pos.checked_add(vendor).ok_or_else(||Error::damaged("comment overflow"))?;if pos>d.len(){return Err(Error::damaged("truncated Vorbis vendor"));}let n=take32(d,&mut pos)?;for _ in 0..n{let z=take32(d,&mut pos)?;pos=pos.checked_add(z).ok_or_else(||Error::damaged("comment overflow"))?;if pos>d.len(){return Err(Error::damaged("truncated Vorbis comment"));}}if d.get(pos).copied().unwrap_or(0)&1==0{return Err(Error::damaged("Vorbis comment framing bit"));}Ok(())}
fn validate_setup(p:&[u8])->Result<()> {let d=header(p,5)?;let mut b=Bits::new(d);let books=usize::try_from(b.read(8)?).map_err(|_|Error::damaged("codebook count"))?.saturating_add(1);for _ in 0..books{if b.read(24)?!=0x564342{return Err(Error::damaged("Vorbis codebook sync"));}let _dims=b.read(16)?;let entries=b.read(24)?;if entries>1_000_000{return Err(Error::Refused("Vorbis codebook entry limit exceeded".to_owned()));}let ordered=b.read(1)?!=0;if ordered{let mut current=0u32;let _len=b.read(5)?.saturating_add(1);while current<entries{let remain=entries.saturating_sub(current);let bits=32u32.saturating_sub(remain.leading_zeros());let n=if bits==0{0}else{b.read(u8::try_from(bits).map_err(|_|Error::damaged("codebook bits"))?)?};if n==0||n>remain{return Err(Error::damaged("invalid ordered Vorbis codebook"));}current=current.saturating_add(n);}}else{let sparse=b.read(1)?!=0;for _ in 0..entries{if !sparse||b.read(1)?!=0{let _=b.read(5)?;}}}let lookup=b.read(4)?;if lookup>2{return Err(Error::damaged("Vorbis codebook lookup type"));}if lookup!=0{let _=b.read(32)?;let _=b.read(32)?;let value_bits=b.read(4)?.saturating_add(1);let _=b.read(1)?;let values=if lookup==1{entries}else{entries.saturating_mul(u32::from(_dims))};if values>4_000_000{return Err(Error::Refused("Vorbis codebook lookup limit exceeded".to_owned()));}for _ in 0..values{let _=b.read(u8::try_from(value_bits).map_err(|_|Error::damaged("lookup bits"))?)?;}}}Ok(())}
/// Decodes an Ogg/Vorbis-I stream. Header/resource validation is performed before PCM allocation.
pub fn decode(input:&[u8],maximum_samples:usize)->Result<Pcm>{let p=ogg::packets(input)?;let id=p.first().ok_or_else(||Error::damaged("missing Vorbis identification"))?;let comment=p.get(1).ok_or_else(||Error::damaged("missing Vorbis comment"))?;let setup=p.get(2).ok_or_else(||Error::damaged("missing Vorbis setup"))?;let(ch,rate,_,_)=identification(&id.data)?;validate_comment(&comment.data)?;validate_setup(&setup.data)?;let granule=p.iter().rev().find_map(|x|x.granule).ok_or_else(||Error::damaged("Vorbis stream has no final granule"))?;let frames=usize::try_from(granule).map_err(|_|Error::Refused("Vorbis sample count too large".to_owned()))?;let samples=frames.checked_mul(usize::from(ch)).ok_or_else(||Error::damaged("Vorbis sample count overflow"))?;if samples>maximum_samples{return Err(Error::Refused("Vorbis sample limit exceeded".to_owned()));}Err(Error::Refused("Vorbis audio packet synthesis is not implemented yet".to_owned()))}
#[cfg(test)]mod tests{use super::*;#[test]fn huge_codebook_is_refused_before_allocation(){let mut d=vec![5];d.extend_from_slice(b"vorbis");d.push(0);d.extend_from_slice(&[0x42,0x43,0x56,1,0,0,0xff,0xff,0xff]);assert!(validate_setup(&d).is_err());}}