// Generated by tools/generate_unicode_tables.py from Unicode 17.0.0 UCD.
const TABLE_SECTIONS: [TableSection; 4] = [
    TableSection {
        offset: 24,
        count: 1386,
        stride: 9,
        class_offset: Some(8),
    },
    TableSection {
        offset: 12498,
        count: 2917,
        stride: 9,
        class_offset: Some(8),
    },
    TableSection {
        offset: 38751,
        count: 156,
        stride: 8,
        class_offset: None,
    },
    TableSection {
        offset: 39999,
        count: 473,
        stride: 9,
        class_offset: Some(8),
    },
];
const TABLE_END: usize = 44256;
