[package]
name = "sse-update"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sse-core = { path = "../sse-core" }
sse-codecs = { path = "../sse-codecs" }
sse-sys = { path = "../sse-sys" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[lints]
workspace = true
